### ISSUE TITLE
First test of dataset in Schema.org

### ISSUE THREAD

**Issue by ypriverol** [OmicsDI/ddi-web-app#135]
Hi all:
 Thanks to @Ricardo-Ke @ggcong and @mindcrusher11 we did the first validation of the datasets with
 the schema.org. I sent an email to the schema.org & google developers @danbri to show them our 
 work. They did a first validation and give us a nice report about our representation, I put some 
 comments inside using `code code`, remeber that the definition of science dataset is this one 
 http://schema.org/Dataset: 
 
Report
----------
Looking at your data in the structured data testing tool, a couple of things to note:

- [ ]  the updated predicate name us variableMeasured  (note the singular). `This mean that the variable is called **variableMeasured**. If we want to use multiple variables we need repeat variableMeasured`

- [ ]  I also wonder if you have something more for "creator" than just @type (type by itself is not very meaningful). Maybe you have it filled in for others? 
 - `Here we should be careful, for example the following dataset http://www.omicsdi.org/dataset/arrayexpress-repository/E-MTAB-4995 do not have creator, them we should remove this field rather than provide an empty object`. 
 - `For the creators we should add the submitter details, Principal investigator if is provided (PRIDE). We should try to recover all this information if is available. ` 
 - `In the author we should try to fill it with all authors in the piublication related with the dataset.` Authors will be the first and last authors` 
 - `contributor will be all other authors of the paper.` 
 - `for all the authors, creators, contributors we should try to get the affiliation (Organization), etc.`   

- [ ]  It also seems that you should be able to specify includedInCatalog for many of these, no? `This is a feature that we need to look in the future, this basically are consortium datasets.` `I will observe this carefully but we will not implemented for now.` 
 
- [ ]  If you have access to bibliographic citations, that would be even better. `Here, we need to finally include the citation of the dataset and the paper, we should include both. For the dataset will be something like`: 

> ![image](https://cloud.githubusercontent.com/assets/52113/19885695/ee0cfd26-a017-11e6-9d47-0ba3dfc2f0ff.png)
A couple of notes, authors are the submitter and PI, year is the year of publication, Title is the dataset title, the Database is the database provider, Version is always V1 (for now), DOI if is avialable. 

For each publication related with the dataset we should generate also the citation in the json-ld 

> for the publication we should try to implement a simple script like this:  https://github.com/CIDARLAB/pubmedAPI

If you want to read more about Dataset implementation and discussions in Schema.org this is a nice thread https://github.com/schemaorg/schemaorg/issues/1083

**Comment by baimingze** [comment]
@data{ ST000106,
authors = {a1, a2},
PublicationData = {2012.08},
TitleOfTheDataset = {IWMS Study 1 Weight comparison of obese and lean patients},
Database = {MetabolomicsWorkbench},
version = {V1},
originalUrl = {http://www.metabolomicsworkbench.org/data/DRCCMetadata.php?Mode=Study&StudyID=ST000106}
}

**Comment by baimingze** [comment]
@yasset, for the first item,

there is no variableMesuared, but variablesMesuraed in the http://pending.schema.org/Dataset

**Comment by ypriverol** [comment]
Hi @baimingze, @mindcrusher11 is working to get most of the information from the web service. including dates, authors, etc. He will say when all the information is ready and he will let us know. 

Regards 
Yasset

**Comment by mindcrusher11** [comment]
@ypriverol @baimingze 
Can someone help me with corresponding fields for authors and dates ?

thanks
gaurhari

**Comment by VladimirAlexiev** [comment]
@baimingze wrong: you should use multiple values of http://pending.schema.org/variableMeasured. If you look up http://pending.schema.org/variablesMeasured, you'll see it says it's in the "attic", i.e. deprecated.

You can always use a property multiple times with RDF. Putting multiple values in one triples (eg by concatenating them) is always wrong, that's why Schema has deprecated several props using names in the plural, and replaced with singular.

**Comment by ypriverol** [comment]
Thanks @VladimirAlexiev we have fixed that in the implementation.
