### ISSUE TITLE
Problem with characters

### ISSUE THREAD

**Issue by ypriverol** [OmicsDI/ddi-web-app#139]
Hi @Ricardo-Ke :

Can you take a look to the character encoding of this dataset. I have seen this problem in others but this one in particular looks really like a mess. 

Regards 
Yasset

<img width="1268" alt="screen shot 2016-11-24 at 17 04 44" src="https://cloud.githubusercontent.com/assets/52113/20606365/5bafa470-b268-11e6-9b84-38135369d7b6.png">

**Comment by baimingze** [comment]
the character issue may come from original data:

https://www.ebi.ac.uk/pride/archive/projects/PXD000004
http://www.omicsdi.org/ws/dataset/get?acc=PXD000004&database=pride
both have this charactor issue.

ANOTHER issue of this page is:

Some of the sentences have repeated many times.

![20161125105946](https://cloud.githubusercontent.com/assets/3970400/20613380/56703196-b2fe-11e6-94ab-a95ff6ac6a25.png)

**Comment by ypriverol** [comment]
@baimingze I know the problems comes from the original provider. But do we have a way to clean this. We need to think about possible solutions.
